services:
  bot:
    build: .
    command: python launcher.py
    volumes:
      - .:/bot
  database:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
  cache:
    image: redis
    volumes:
      - redis:/data

volumes:
  postgresql:
  redis:
