services:
  bot:
    build: .
    command: python launcher.py
    volumes:
      - .:/bot
  database:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
